### ISSUE TITLE
Extension gives error

### ISSUE THREAD

**Issue by samer-faour-exa** [jdifeder/exabeam-enhancement-suite#1]
'content_security_policy': CSP directive 'script-src' must be specified (either explicitly, or implicitly via 'default-src') and must whitelist only secure resources.

`{
    "name": "Exabeam Enhancement Suite",
    "version": "0.1",
    "description": "Enhance Exabeam Advanced Analytics",
    "manifest_version": 2,
    "key": "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsUyZX8wycL6zY104rYgQNdF3umqlPt4h+m6gaWphUrCI+joNVLgVhHNS1hZVeMJ7T7cVRUKu7/b3c2ylT/u8+XxvpP+4ind7Dj5y6wbVKFnPn+POgb891dL/f+eDS1nfPUrJHO+fdoKaES/1IabubGfRP7RXQzvu2tp3XdIcYQe0aUbT9GxmEu7F8pEeNbfcm0OwhhSrLdHa+T7NTruCl8FxKrldXcZJPc6UKFKxGYl7/xz6kKaj7URZfy9vwOurlv5OqkyxZkfGeUjCFhhrR9ANU1RDTCjF09NaKEMmihI4u9FmRME3YHeKHrDlE4tC7Biny8OJ+XEsutCIINzSuQIDAQAB",
    "permissions": [
        "tabs",
        "activeTab",
        "webNavigation",
        "<all_urls>",
        "https://*/uba/*",
        "https://api.github.com/*",
        "https://github.com/*"
    ],
    "content_scripts": [
        {
          "matches": ["https://*/uba/*"],
          "run_at": "document_idle",
          "js": ["THsearch.js"]
        }
    ],
    "content_security_policy": "script-src-elem http://localhost:8097 http://localhost:8098 chrome-extension://*",
    "web_accessible_resources": [
        "index.html",
        "*.css",
        "*.js",`

**Comment by jdifeder** [comment]
Odd that I don't get that error, but I beleive it's complaining about trying to load a local resource I use during development. I commented that out and made a new release.

Please try the latest release. [v0.199](https://github.com/jdifeder/exabeam-enhancement-suite/releases/tag/v0.199)

**Comment by samer-faour-exa** [comment]
Cool. All good now. No error.

FYI it seemed to be working even with the error.

I will play around with this a bit more between now and next week.

**Comment by samer-faour-exa** [comment]
I spoke too soon. Another one:

SharedArrayBuffer will require cross-origin isolation as of M91, around May 2021. See https://developer.chrome.com/blog/enabling-shared-array-buffer/ for more details.

Stack Trace
static/js/2.807c6d58.chunk.js:63132 (anonymous function)

Line 63132:
typeof SharedArrayBuffer === 'function' ? new SharedArrayBuffer(profilingStateSize * Int32Array.BYTES_PER_ELEMENT) : // $FlowFixMe Flow doesn't know about ArrayBuffer

These show up as Errors here: chrome://extensions/
