### ISSUE TITLE
SharedArrayBuffer error

### ISSUE THREAD

**Issue by samer-faour-exa** [jdifeder/exabeam-enhancement-suite#2]
SharedArrayBuffer will require cross-origin isolation as of M91, around May 2021. See https://developer.chrome.com/blog/enabling-shared-array-buffer/ for more details.

Stack Trace
static/js/2.807c6d58.chunk.js:63132 (anonymous function)

Line 63132:
typeof SharedArrayBuffer === 'function' ? new SharedArrayBuffer(profilingStateSize * Int32Array.BYTES_PER_ELEMENT) : // $FlowFixMe Flow doesn't know about ArrayBuffer

These show up under Errors here: chrome://extensions/

**Comment by jdifeder** [comment]
This is a React wide issue that they acknowledged and should be fixed in the next few weeks:
https://github.com/facebook/react/pull/20831

**Comment by gaearon** [comment]
17.0.2 is out with the fix. (But there was no real problem, it's a false positive.)

**Comment by jdifeder** [comment]
Thank you! I verified 17.0.2 resolved the issue. I will push this in the next release.
