### ISSUE TITLE
Event list comes up blank

### ISSUE THREAD

**Issue by samer-faour-exa** [jdifeder/exabeam-enhancement-suite#3]
In some cases no events are shown but the sessions are. Wondering if this is something you have come across.

**Comment by samer-faour-exa** [comment]
https://user-images.githubusercontent.com/66428833/112002365-2dce1300-8af6-11eb-812f-001eb9b2a7a2.mov

**Comment by samer-faour-exa** [comment]
[https://drive.google.com/drive/folders/1MIbrIXQkDmBlMQdrhcLUnsctTXji7H-6?usp=sharing](url)

**Comment by jdifeder** [comment]
I beleive this is a product bug in Advanced Analytics and not an issue with the tool.

In rare cases a rule trigger references an event_id that no longer exists for some reason.
I have validated by navigating the timeline in question naturally in AA. When clicking on "Show Event" next to the rule, it returns null.
